# Generated by Django 4.1.3 on 2022-12-02 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_onedsaportion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onedsaportion',
            name='date8',
        ),
        migrations.RemoveField(
            model_name='onedsaportion',
            name='por8',
        ),
        migrations.RemoveField(
            model_name='onedsaportion',
            name='sub8',
        ),
    ]
