# Generated by Django 4.1.3 on 2022-12-04 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_onedsatimetable_saturdaypn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onedsatimetable',
            name='saturdayfn',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='onedsatimetable',
            name='saturdaypt',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
