# Generated by Django 4.1.3 on 2022-12-04 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_onedsatimetable_saturdayfn_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onedsatimetable',
            old_name='saturdaypn',
            new_name='saturdayfn1',
        ),
        migrations.RenameField(
            model_name='onedsatimetable',
            old_name='saturdaypt',
            new_name='saturdayfn2',
        ),
    ]
