# Generated by Django 4.1.3 on 2022-12-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_onedsasit'),
    ]

    operations = [
        migrations.AddField(
            model_name='onedsa',
            name='eight',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='onedsa',
            name='eleven',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='onedsa',
            name='fifteen',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='onedsa',
            name='fourteen',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='onedsa',
            name='nine',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='onedsa',
            name='ten',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='onedsa',
            name='thirteen',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='onedsa',
            name='twelve',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='onedsa',
            name='five',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='onedsa',
            name='four',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='onedsa',
            name='seven',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='onedsa',
            name='six',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='onedsa',
            name='subject',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='onedsa',
            name='three',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='onedsa',
            name='two',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
